# Generated by Django 2.2.12 on 2020-06-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customertype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='facilitytype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='itemtype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='measurementunit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='program',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='slug',
        ),
    ]
